#
# Copyright (c) 2022, 2024, Oracle and/or its affiliates. All rights reserved.
# Copyright (c) 2025, the Jeandle-JDK Authors. All rights reserved.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# This code is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 only, as
# published by the Free Software Foundation.  Oracle designates this
# particular file as subject to the "Classpath" exception as provided
# by Oracle in the LICENSE file that accompanied this code.
#
# This code is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# version 2 for more details (a copy is included in the LICENSE file that
# accompanied this code).
#
# You should have received a copy of the GNU General Public License version
# 2 along with this work; if not, write to the Free Software Foundation,
# Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
# or visit www.oracle.com if you need additional information or have any
# questions.
#

name: 'OpenJDK GHA Sanity Checks'

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:

  ###
  ### Determine platforms to include
  ###

  prepare:
    name: 'Prepare the run'
    runs-on: ubuntu-22.04
    outputs:
      linux-x64: true # We always run test on x86
      linux-aarch64: ${{ contains(github.event.pull_request.labels.*.name, 'AArch64') }}
      linux-riscv64: ${{ contains(github.event.pull_request.labels.*.name, 'RISC-V') }}

    steps:
      - name: 'Checkout the scripts'
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            make/conf/github-actions.conf

      - name: 'Build JTReg'
        id: jtreg
        uses: ./.github/actions/build-jtreg

  ###
  ### Build jobs
  ###

  build-linux-x64:
    name: linux-x64
    needs: prepare
    uses: ./.github/workflows/build-linux.yml
    with:
      platform: linux-x64
      gcc-major-version: '10'
      configure-arguments: ${{ github.event.inputs.configure-arguments }}
      make-arguments: ${{ github.event.inputs.make-arguments }}
      runs-on: ubuntu-22.04
    if: needs.prepare.outputs.linux-x64 == 'true'

  build-linux-aarch64:
    name: linux-aarch64
    needs: prepare
    uses: ./.github/workflows/build-linux.yml
    with:
      platform: linux-aarch64
      gcc-major-version: '10'
      configure-arguments: ${{ github.event.inputs.configure-arguments }}
      make-arguments: ${{ github.event.inputs.make-arguments }}
      runs-on: ubuntu-22.04-arm
    if: needs.prepare.outputs.linux-aarch64 == 'true'

  build-linux-riscv64:
    name: linux-riscv64
    needs: prepare
    uses: ./.github/workflows/build-linux.yml
    with:
      platform: linux-riscv64
      gcc-major-version: '10'
      configure-arguments: ${{ github.event.inputs.configure-arguments }}
      make-arguments: ${{ github.event.inputs.make-arguments }}
      runs-on: riscv-builders
    if: needs.prepare.outputs.linux-riscv64 == 'true'

  ###
  ### Test jobs
  ###

  test-linux-x64:
    name: linux-x64
    needs:
      - build-linux-x64
    uses: ./.github/workflows/test.yml
    with:
      platform: linux-x64
      bootjdk-platform: linux-x64
      runs-on: ubuntu-22.04

  test-linux-aarch64:
    name: linux-aarch64
    needs:
      - build-linux-aarch64
    uses: ./.github/workflows/test.yml
    with:
      platform: linux-aarch64
      bootjdk-platform: linux-aarch64
      runs-on: ubuntu-22.04-arm

  test-linux-riscv64:
    name: linux-riscv64
    needs:
      - build-linux-riscv64
    uses: ./.github/workflows/test.yml
    with:
      platform: linux-riscv64
      bootjdk-platform: linux-riscv64
      runs-on: riscv-builders

  # # Remove bundles so they are not misconstrued as binary distributions from the JDK project
  # remove-bundles:
  #   name: 'Remove bundle artifacts'
  #   runs-on: ubuntu-22.04
  #   if: always()
  #   needs:
  #     - build-linux-x64

  #   steps:
  #     - name: 'Remove bundle artifacts'
  #       run: |
  #         # Find and remove all bundle artifacts
  #         FIXME: recover later
  #         echo "FIXME: don't remove bundles now, recover later"
  #         # See: https://docs.github.com/en/rest/actions/artifacts?apiVersion=2022-11-28
  #         ALL_ARTIFACT_IDS="$(curl -sL \
  #             -H 'Accept: application/vnd.github+json' \
  #             -H 'Authorization: Bearer ${{ github.token }}' \
  #             -H 'X-GitHub-Api-Version: 2022-11-28' \
  #             '${{ github.api_url }}/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts?per_page=100')"
  #         BUNDLE_ARTIFACT_IDS="$(echo "$ALL_ARTIFACT_IDS" | jq -r -c '.artifacts | map(select(.name|startswith("bundles-"))) | .[].id')"
  #         for id in $BUNDLE_ARTIFACT_IDS; do
  #           echo "Removing $id"
  #           curl -sL \
  #               -X DELETE \
  #               -H 'Accept: application/vnd.github+json' \
  #               -H 'Authorization: Bearer ${{ github.token }}' \
  #               -H 'X-GitHub-Api-Version: 2022-11-28' \
  #               "${{ github.api_url }}/repos/${{ github.repository }}/actions/artifacts/$id" \
  #           || echo "Failed to remove bundle"
  #         done
